### ISSUE TITLE
string_of_fdec1 type

### ISSUE THREAD

**Issue by frank-zhang-bam** [tianqizhao-louis/Crust#7]
microC can only do this:
int a;
int b;
a = 1;
b = 2;
print (a);

but not:
int a;
int b;
a = 1;
print (a);
b = 2;

in src2, we implemented a new type, local_or_body, to fix this issue by letting the program decide if the next line of code is body or statement.

**Comment by afsong** [comment]
When I try 
```
int a;
int b;
a = 1;
```
I get this error: `Fatal error: exception Stdlib.Parsing.Parse_error`

**Comment by tianqizhao-louis** [comment]
solved
